apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    # example config content
    some: config

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: main
      image: alpine
      command: [sh, -c, 'while true ; do date ; cat /vol/config.yaml ; sleep 5 ; done']
      volumeMounts:
        - name: vol
          mountPath: /vol
  volumes:
    - name: vol
      configMap:
        name: configmap
        items:
          - key: config.yaml
            path: config.yaml
