apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: main
      image: alpine
      command: [sh, -c, 'while true ; do date ; df -h /vol ; ls -la /vol ; sleep 5 ; done']
      volumeMounts:
        - name: vol
          mountPath: /vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-wait-delete
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: main
      image: alpine
      command: [sh, -c, 'while true ; do date ; df -h /vol ; ls -la /vol ; sleep 5 ; done']
      volumeMounts:
        - name: vol
          mountPath: /vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-wait-delete
