apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ebs-immediate-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wait-delete
spec:
  storageClassName: ebs-wait-delete
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
