apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-immediate-retain
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-wait-delete
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
