kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azdisk
provisioner: kubernetes.io/azure-disk
parameters:
  kind: managed
  storageaccounttype: Standard_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
